name: Run Scraping Every 3 Days at 17:00

on:
  schedule:
    # Runs at 17:00 UTC every 3 days
    - cron: "0 17 */3 * *"
  workflow_dispatch:
jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.7"
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install
      - name: Run the script
        run: pipenv run python3 scraping/run_scraper.py
        env:
          START_URL_2DAYS: ${{ secrets.START_URL_2DAYS }}
          START_URL_7DAYS: ${{ secrets.START_URL_7DAYS }}
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          AZURE_CONTAINER_NAME: ${{ secrets.AZURE_CONTAINER_NAME }}
      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Auto-update data files
