name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev
          # Ensure your Pipfile includes your testing libraries

      - name: Run tests with pytest
        run: |
          pipenv run pytest
